apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-internal-policy
  namespace: {{ .Values.namespace | default "epharmacy" }}
spec:
  podSelector:
    matchLabels:
      role: {{ .Values.role | default "backend" }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
      namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443

  - from:
    - podSelector:
        matchLabels:
          role: frontend
      namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace | default "epharmacy" }}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443

  egress:
  - to:
    - podSelector:
        matchLabels:
          role: frontend
      namespaceSelector:
        matchLabels:
          name: epharmacy
    ports:
    - protocol: TCP
      port: 6100

  - to:
    - ipBlock:
        cidr: 172.30.16.1/32  # DB IP
    ports:
    - protocol: TCP
      port: 1433

  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

