apiVersion: v1
kind: secret
metadata:
  name: backend-secret
  namespace: Epharmacy
type: Opaque
data:
  DB_USERNAME: Rahul
  DB_PASSWORD: Rahul@123
  DB_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
  CART_DB_URL: jdbc:sqlserver://localhost:1433;databaseName=EPHARMACY_CARTMS_DB;encrypt=false
  LOGIN_DB_URL: jdbc:sqlserver://localhost:1433;databaseName=EPHARMACY_LOGINMS_DB;encrypt=false
  MEDICINE-DB_URL: jdbc:sqlserver://localhost:1433;databaseName=EPHARMACY_MEDICINEMS_DB;encrypt=false
  ORDER_DB_URL: jdbc:sqlserver://localhost:1433;databaseName=EPHARMACY_ORDERMS_DB;encrypt=false
  PAYMENT_DB_URL: jdbc:sqlserver://localhost:1433;databaseName=EPHARMACY_PAYMENTMS_DB;encrypt=false
  CUSTOMER_DB_URL: jdbc:sqlserver://localhost:1433;databaseName=EPHARMACY_CUSTOMERMS_DB;encrypt=false



  