-- Updated for Microsoft SQL Server
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'EPHARMACY_CARTMS_DB')
BEGIN
    DROP DATABASE EPHARMACY_CARTMS_DB;
END
GO

CREATE DATABASE EPHARMACY_CARTMS_DB;
GO

USE EPHARMACY_CARTMS_DB;
GO

CREATE TABLE CUSTOMER_CART (
    CART_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT,
    MEDICINE_ID INT,
    QUANTITY SMALLINT
);
GO

INSERT INTO CUSTOMER_CART (CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (101, 1011, 2);
INSERT INTO CUSTOMER_CART (CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (102, 1020, 1);
INSERT INTO CUSTOMER_CART (CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (103, 1030, 1);
INSERT INTO CUSTOMER_CART (CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (104, 1030, 1);
INSERT INTO CUSTOMER_CART (CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (105, 1022, 3);
GO

SELECT * FROM CUSTOMER_CART;
GO

COMMIT;
