-- Updated for Microsoft SQL Server
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'EPharmacy_OrderMS_DB')
BEGIN
    DROP DATABASE EPharmacy_OrderMS_DB;
END
GO

CREATE DATABASE EPharmacy_OrderMS_DB;
GO

USE EPharmacy_OrderMS_DB;
GO

CREATE TABLE ORDER_DETAILS(
    ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
    MRP_TOTAL DECIMAL(7,2),
    DISCOUNT_PERCENT INT,
    DISCOUNTED_TOTAL DECIMAL(7,2),
    DELIVERY_DATE DATETIME,
    CUSTOMER_ID INT,
    ORDER_STATUS NVARCHAR(20) CHECK (ORDER_STATUS IN ('PROCESSING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    ORDER_DATE DATETIME,
    CANCEL_REASON NVARCHAR(500),
    ADDRESS_ID INT,
    DELIVERY_STATUS NVARCHAR(30) CHECK (DELIVERY_STATUS IN ('AWAITING_CONFIRMATION', 'DELIVERED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'CANCELLED')),
    CARD_ID NVARCHAR(16)
);
GO

CREATE TABLE ORDERED_MEDICINE(
    ORDERED_MEDICINE_ID INT IDENTITY(1,1) PRIMARY KEY,
    ORDERED_QUANTITY INT,
    ORDER_SUBTOTAL DECIMAL(7,2),
    MEDICINE_ID INT,
    ORDER_ID INT FOREIGN KEY REFERENCES ORDER_DETAILS(ORDER_ID)
);
GO
