global:
  namespace: epharmacy
  role: backend
  version: v1

replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

services:
  authValidation:
    name: auth-validation
    image: auth-validation:v1
    containerPort: 1100
    serviceAccountName: backend-sa
    securityContext:
      runAsUser: 1000
    tolerations:
      - key: "nodeType"
        operator: "Equal"
        value: "Node01"
        effect: "NoSchedule"
    nodeSelector:
      nodeType: Node01
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 200
      periodSeconds: 10

  credentialsValidation:
    name: auth-credentials-validation
    image: auth-credentials-validation:v1
    containerPort: 1300
    serviceAccountName: backend-sa
    securityContext:
      runAsUser: 1000
    tolerations:
      - key: "nodeType"
        operator: "Equal"
        value: "Node01"
        effect: "NoSchedule"
    nodeSelector:
      nodeType: Node01
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
    readinessProbe:
      initialDelaySeconds: 130
      periodSeconds: 25
    livenessProbe:
      initialDelaySeconds: 210
      periodSeconds: 15

  entitlementValidation:
    name: auth-entitlement-validation
    image: auth-entitlement-validation:v1
    containerPort: 1400
    serviceAccountName: backend-sa
    securityContext:
      runAsUser: 1000
    tolerations:
      - key: "nodeType"
        operator: "Equal"
        value: "Node01"
        effect: "NoSchedule"
    nodeSelector:
      nodeType: Node01
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
    readinessProbe:
      initialDelaySeconds: 110
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 190
      periodSeconds: 10

  deviceValidation:
    name: auth-device-validation
    image: auth-device-validation:v1
    containerPort: 1500
    serviceAccountName: backend-sa
    securityContext:
      runAsUser: 1000
    tolerations:
      - key: "nodeType"
        operator: "Equal"
        value: "Node01"
        effect: "NoSchedule"
    nodeSelector:
      nodeType: Node01
    resources:
      requests:
        memory: "512Mi"
        cpu: "300m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    readinessProbe:
      initialDelaySeconds: 125
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 195
      periodSeconds: 10

  sessionValidation:
    name: auth-session-validation
    image: auth-session-validation:v1
    containerPort: 1600
    serviceAccountName: backend-sa
    securityContext:
      runAsUser: 1000
    tolerations:
      - key: "nodeType"
        operator: "Equal"
        value: "Node01"
        effect: "NoSchedule"
    nodeSelector:
      nodeType: Node01
    resources:
      requests:
        memory: "1Gi"
        cpu: "400m"
      limits:
        memory: "1.5Gi"
        cpu: "800m"
    readinessProbe:
      initialDelaySeconds: 130
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 210
      periodSeconds: 10

  rsaValidation:
    name: auth-rsa
    image: auth-rsa:v1
    containerPort: 1700
    serviceAccountName: backend-sa
    securityContext:
      runAsUser: 1000
    tolerations:
      - key: "nodeType"
        operator: "Equal"
        value: "Node01"
        effect: "NoSchedule"
    nodeSelector:
      nodeType: Node01
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    readinessProbe:
      initialDelaySeconds: 140
      periodSeconds: 25
    livenessProbe:
      initialDelaySeconds: 220
      periodSeconds: 10

  accessValidation:
    name: auth-access
    image: auth-access:v1
    containerPort: 1200
    serviceAccountName: 
    securityContext:
      runAsUser: 1000
    tolerations:
      - key: "nodeType"
        operator: "Equal"
        value: "Node01"
        effect: "NoSchedule"
    nodeSelector:
      nodeType: Node01
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 200
      periodSeconds: 10
env:
  authConfigMap: auth-config-prod
  backendConfigMap: backend-config-prod
  authSecret: auth-secret-prod
  backendSecret: backend-secret-prod