apiVersion: v1
<<<<<<< HEAD
kind: secret
metadata:
  name: auth-secret
  namespace: Epharmacy-backend
  labels:
    app: Epharmacy-application 
type: Opaque
data:
  REDIS_URL: <base64-encoded-redis-url>  # Replace with actual base64 encoded values
  REDIS_HOST: <base64-encoded-redis-host>  # Replace with actual base64 encoded values
  REDIS_PORT: <base64-encoded-redis-port>  # Replace with actual base64 encoded values
  REDIS_USERNAME: <base64-encoded-redis-username>  # Replace with actual base64 encoded values
  REDIS_PASSWORD: <base64-encoded-redis-password>  # Replace with actual base64 encoded values
  JWT_KEY: <base64-encoded-jwt-key>  # Replace with actual base64 encoded values
  JWT_KEY1: <base64-encoded-jwt-key1>  # Replace with actual base64 encoded values
  LDAP.USERNAME: "admin.example.com"
  LDAP.PASSWORD: "Rahul@123"
=======
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ include "auth-service.name" . }}
type: Opaque
data:
  REDIS_URL: {{ .Values.secret.REDIS_URL | quote }}
  REDIS_HOST: {{ .Values.secret.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.secret.REDIS_PORT | quote }}
  REDIS_USERNAME: {{ .Values.secret.REDIS_USERNAME | quote }}
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD | quote }}
  JWT_KEY: {{ .Values.secret.JWT_KEY | quote }}
  JWT_KEY1: {{ .Values.secret.JWT_KEY1 | quote }}
  LDAP.USERNAME: {{ .Values.secret.LDAP_USERNAME | quote }}
  LDAP.PASSWORD: {{ .Values.secret.LDAP_PASSWORD | quote }}
>>>>>>> 5af0e54ac896d945d64acb946e037842bfa9b7cd
