apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name.authEntitlementValidation }}-deployment
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    name: {{ .Values.name.authEntitlementValidation }}
    version: {{ .Values.version | default "v1" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      name: {{ .Values.name.authEntitlementValidation }}
      version: {{ .Values.version | default "v1" }}
  template:
    metadata:
      labels:
        name: {{ .Values.name.authEntitlementValidation }}
        role: {{ .Values.role | default "backend" }}
        version: {{ .Values.version | default "v1" }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "default" }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
        runAsNonRoot: true
      tolerations:
        - key: "nodeType"
          operator: "Equal"
          value: {{ .Values.tolerations.nodeTypeValue | default "Node01" }}
          effect: "NoSchedule"
      nodeSelector:
        node-type: {{ .Values.nodeSelector.nodeType | default "Node01" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodeType
                    operator: In
                    values:
                      - {{ .Values.nodeSelector.nodeType | default "Node01" }}
      containers:
        - name: authEntitlementValidation
          image: {{ .Values.image.authEntitlementValidation }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.containerPort | default 1100 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.env.authConfigMap | default (include "auth-service.fullname" . ) }}-config
            - configMapRef:
                name: {{ .Values.env.backendConfigMap | default "backend-config" }}
            - secretRef:
                name: {{ .Values.env.authSecret | default (include "auth-service.fullname" . ) }}-secret
            - secretRef:
                name: {{ .Values.env.backendSecret | default "backend-secret" }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | quote }}
              cpu: {{ .Values.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort | default 1100 }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 120 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 20 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort | default 1100 }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 200 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.authEntitlementValidation }}-service
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    name: {{ .Values.name.authEntitlementValidation }}
    role: {{ .Values.role | default "backend" }}
    version: {{ .Values.version | default "v1" }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.containerPort | default 1100 }}
      protocol: TCP
    - name: https
      port: 443
      targetPort: {{ .Values.containerPort | default 1100 }}
      protocol: TCP
  selector:
    name: {{ .Values.name.authEntitlementValidation }}
    role: {{ .Values.role | default "backend" }}
    version: {{ .Values.version | default "v1" }}
