apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: Epharmacy-frontend-hpa
  namespace: Epharmacy  # <-- matches the Deployment namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Epharmacy-frontend       # <-- matches the Deployment name
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: pods
      pods:
        metric: 
          name: "{{ .Values.metric.name }}"  # Use the metric name from values.yaml
          target: 
            type: "{{ .Values.metric.target.type }}"  # Use the target type from values.yaml
            averageValue: "{{ .Values.metric.target.averageValue }}" 
        
