-- Updated for Microsoft SQL Server
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'EPharmacy_PaymentMS_DB')
BEGIN
    DROP DATABASE EPharmacy_PaymentMS_DB;
END
GO

CREATE DATABASE EPharmacy_PaymentMS_DB;
GO

USE EPharmacy_PaymentMS_DB;
GO

CREATE TABLE CARD(
    CARD_ID NVARCHAR(16) PRIMARY KEY,
    NAME_ON_CARD NVARCHAR(50),
    CVV NVARCHAR(70),
    CARD_TYPE NVARCHAR(20) CHECK (CARD_TYPE IN ('DEBIT_CARD', 'CREDIT_CARD')),
    EXPIRY_DATE DATE,
    CUSTOMER_ID INT
);
GO

CREATE TABLE PAYMENT(
    PAYMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PAYMENT_TIME DATETIME,
    AMOUNT DECIMAL(10,2),
    CARD_ID NVARCHAR(16) FOREIGN KEY REFERENCES CARD(CARD_ID),
    CUSTOMER_ID INT
);
GO
