apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: monitoring-pvc
    namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azure-disk-sc
  resources:
    requests:
      storage: 5Gi