apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-config
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ include "auth-service.name" . }}
data:
  server.servlet.context-path: {{ .Values.configmap.serverContextPath | quote }}
  auth.base.Url: {{ .Values.configmap.authBaseUrl | quote }}
  successRedirectUrl: {{ .Values.configmap.successRedirectUrl | quote }}
  auth-api: {{ .Values.configmap.authApi | quote }}
  auth-access-api: {{ .Values.configmap.authAccessApi | quote }}
  auth-access.base.Url: {{ .Values.configmap.authAccessBaseUrl | quote }}
  auth-credentialsValidation-api: {{ .Values.configmap.authCredentialsValidationApi | quote }}
  auth-credentialsValidation.base.Url: {{ .Values.configmap.authCredentialsValidationBaseUrl | quote }}
  auth-entitlementValidation-api: {{ .Values.configmap.authEntitlementValidationApi | quote }}
  auth-entitlementValidation.base.Url: {{ .Values.configmap.authEntitlementValidationBaseUrl | quote }}
  auth-deviceValidation-api: {{ .Values.configmap.authDeviceValidationApi | quote }}
  auth-deviceValidation.base.Url: {{ .Values.configmap.authDeviceValidationBaseUrl | quote }}
  auth-sessionValidation-api: {{ .Values.configmap.authSessionValidationApi | quote }}
  auth-sessionValidation.base.Url: {{ .Values.configmap.authSessionValidationBaseUrl | quote }}
  auth-vendorValidation-api: {{ .Values.configmap.authVendorValidationApi | quote }}
  auth-vendorValidation.base.Url: {{ .Values.configmap.authVendorValidationBaseUrl | quote }}
