apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ include "auth-service.name" . }}
type: Opaque
data:
  REDIS_URL: {{ .Values.secret.REDIS_URL | quote }}
  REDIS_HOST: {{ .Values.secret.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.secret.REDIS_PORT | quote }}
  REDIS_USERNAME: {{ .Values.secret.REDIS_USERNAME | quote }}
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD | quote }}
  JWT_KEY: {{ .Values.secret.JWT_KEY | quote }}
  JWT_KEY1: {{ .Values.secret.JWT_KEY1 | quote }}
  LDAP.USERNAME: {{ .Values.secret.LDAP_USERNAME | quote }}
  LDAP.PASSWORD: {{ .Values.secret.LDAP_PASSWORD | quote }}